/**
 * ImageMessage —  Gemini
 *
 *  tool result  [generated_image:path]
 *  /api/gemini/image/:filename
 */

import { useState } from 'react'
import { Download, Maximize2 } from 'lucide-react'
import ImageLightbox from './ImageLightbox'

export const extractGeneratedImages = (content: string): string[] => {
  const matches = content.match(/\[generated_image:([^\]]+)\]/g)
  if (!matches) return []
  return matches.map((m) => m.replace('[generated_image:', '').replace(']', ''))
}

const getFilename = (path: string): string => path.split('/').pop() || path

const getImageUrl = (path: string): string => `/api/gemini/image/${getFilename(path)}`

export const stripImageMarkers = (content: string): string =>
  content.replace(/\[generated_image:[^\]]+\]/g, '').trim()

const ImageMessage = ({ imagePaths }: { imagePaths: string[] }) => {
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null)
  const [loadErrors, setLoadErrors] = useState<Set<string>>(new Set())

  const handleDownload = (path: string) => {
    const link = document.createElement('a')
    link.href = getImageUrl(path)
    link.download = getFilename(path)
    link.click()
  }

  if (imagePaths.length === 0) return null

  return (
    <>
      <div style={{
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        padding: '6px 0',
      }}>
        {imagePaths.map((path) => {
          const filename = getFilename(path)
          const hasError = loadErrors.has(filename)

          return (
            <div
              key={filename}
              style={{
                position: 'relative',
                borderRadius: 8,
                overflow: 'hidden',
                border: '1px solid rgb(var(--border-subtle))',
                background: 'rgb(var(--bg-elevated))',
                maxWidth: 400,
              }}
            >
              {hasError ? (
                <div style={{
                  width: 300,
                  height: 200,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'rgb(var(--text-muted))',
                  fontSize: 12,
                }}>
                  ImageLoadFailed
                </div>
              ) : (
                <img
                  src={getImageUrl(path)}
                  alt="Generated by Gemini"
                  style={{
                    display: 'block',
                    maxWidth: '100%',
                    maxHeight: 400,
                    cursor: 'pointer',
                  }}
                  onClick={() => setLightboxSrc(getImageUrl(path))}
                  onError={() => setLoadErrors((prev) => new Set(prev).add(filename))}
                />
              )}

              {/* ActionsButton */}
              {!hasError && (
                <div style={{
                  position: 'absolute',
                  top: 6,
                  right: 6,
                  display: 'flex',
                  gap: 4,
                }}>
                  <button
                    onClick={() => setLightboxSrc(getImageUrl(path))}
                    style={{
                      width: 28,
                      height: 28,
                      borderRadius: 6,
                      border: 'none',
                      background: 'rgba(0,0,0,0.5)',
                      color: '#fff',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <Maximize2 size={14} />
                  </button>
                  <button
                    onClick={() => handleDownload(path)}
                    style={{
                      width: 28,
                      height: 28,
                      borderRadius: 6,
                      border: 'none',
                      background: 'rgba(0,0,0,0.5)',
                      color: '#fff',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <Download size={14} />
                  </button>
                </div>
              )}
            </div>
          )
        })}
      </div>

      <ImageLightbox
        src={lightboxSrc}
        onClose={() => setLightboxSrc(null)}
        downloadName={lightboxSrc ? getFilename(lightboxSrc) : undefined}
      />
    </>
  )
}

export default ImageMessage
